export const FORMATIONS = {
  "4-4-2": [
    { id: "GK",  label: "Portier",   x: 50, y: 85, poz: "Portier"   },
    { id: "LB",  label: "Mbrojtës",  x: 12, y: 68, poz: "Mbrojtës"  },
    { id: "CB1", label: "Qendër",    x: 35, y: 68, poz: "Mbrojtës"  },
    { id: "CB2", label: "Qendër",    x: 65, y: 68, poz: "Mbrojtës"  },
    { id: "RB",  label: "Mbrojtës",  x: 88, y: 68, poz: "Mbrojtës"  },
    { id: "LM",  label: "Mesfushor", x: 12, y: 46, poz: "Mesfushor" },
    { id: "CM1", label: "Qendër",    x: 35, y: 46, poz: "Mesfushor" },
    { id: "CM2", label: "Qendër",    x: 65, y: 46, poz: "Mesfushor" },
    { id: "RM",  label: "Mesfushor", x: 88, y: 46, poz: "Mesfushor" },
    { id: "ST1", label: "Sulmues",   x: 35, y: 20, poz: "Sulmues"   },
    { id: "ST2", label: "Sulmues",   x: 65, y: 20, poz: "Sulmues"   },
  ],
  "4-3-3": [
    { id: "GK",  label: "Portier",   x: 50, y: 85, poz: "Portier"   },
    { id: "LB",  label: "Mbrojtës",  x: 12, y: 68, poz: "Mbrojtës"  },
    { id: "CB1", label: "Qendër",    x: 35, y: 68, poz: "Mbrojtës"  },
    { id: "CB2", label: "Qendër",    x: 65, y: 68, poz: "Mbrojtës"  },
    { id: "RB",  label: "Mbrojtës",  x: 88, y: 68, poz: "Mbrojtës"  },
    { id: "CM1", label: "Mesfushor", x: 25, y: 48, poz: "Mesfushor" },
    { id: "CM2", label: "Qendër",    x: 50, y: 48, poz: "Mesfushor" },
    { id: "CM3", label: "Mesfushor", x: 75, y: 48, poz: "Mesfushor" },
    { id: "LW",  label: "Krahësor",  x: 15, y: 22, poz: "Sulmues"   },
    { id: "ST",  label: "Sulmues",   x: 50, y: 18, poz: "Sulmues"   },
    { id: "RW",  label: "Krahësor",  x: 85, y: 22, poz: "Sulmues"   },
  ],
  "3-5-2": [
    { id: "GK",  label: "Portier",   x: 50, y: 85, poz: "Portier"   },
    { id: "CB1", label: "Qendër",    x: 25, y: 68, poz: "Mbrojtës"  },
    { id: "CB2", label: "Qendër",    x: 50, y: 68, poz: "Mbrojtës"  },
    { id: "CB3", label: "Qendër",    x: 75, y: 68, poz: "Mbrojtës"  },
    { id: "LWB", label: "Krahësor",  x: 8,  y: 50, poz: "Mesfushor" },
    { id: "CM1", label: "Mesfushor", x: 30, y: 48, poz: "Mesfushor" },
    { id: "CM2", label: "Qendër",    x: 50, y: 48, poz: "Mesfushor" },
    { id: "CM3", label: "Mesfushor", x: 70, y: 48, poz: "Mesfushor" },
    { id: "RWB", label: "Krahësor",  x: 92, y: 50, poz: "Mesfushor" },
    { id: "ST1", label: "Sulmues",   x: 35, y: 20, poz: "Sulmues"   },
    { id: "ST2", label: "Sulmues",   x: 65, y: 20, poz: "Sulmues"   },
  ],
  "4-2-3-1": [
    { id: "GK",  label: "Portier",   x: 50, y: 85, poz: "Portier"   },
    { id: "LB",  label: "Mbrojtës",  x: 12, y: 68, poz: "Mbrojtës"  },
    { id: "CB1", label: "Qendër",    x: 35, y: 68, poz: "Mbrojtës"  },
    { id: "CB2", label: "Qendër",    x: 65, y: 68, poz: "Mbrojtës"  },
    { id: "RB",  label: "Mbrojtës",  x: 88, y: 68, poz: "Mbrojtës"  },
    { id: "DM1", label: "Mbrojtës",  x: 35, y: 54, poz: "Mesfushor" },
    { id: "DM2", label: "Mbrojtës",  x: 65, y: 54, poz: "Mesfushor" },
    { id: "LW",  label: "Krahësor",  x: 15, y: 36, poz: "Mesfushor" },
    { id: "AM",  label: "Sulmues-M", x: 50, y: 36, poz: "Mesfushor" },
    { id: "RW",  label: "Krahësor",  x: 85, y: 36, poz: "Mesfushor" },
    { id: "ST",  label: "Sulmues",   x: 50, y: 18, poz: "Sulmues"   },
  ],
};
